title: Lou Reade Art
email: your-email@example.com
description: Lou Reade Art - paintings and illustration
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
